# Generated by Django 5.1.3 on 2024-11-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_gameresult_friendrequestmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessagemodel',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
