# Generated by Django 5.1.3 on 2024-11-30 17:22

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='default', max_length=10)),
                ('level', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('consecutive_wins', models.IntegerField(default=0)),
                ('max_consecutive_wins', models.IntegerField(default=0)),
                ('achievements', models.IntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('total_fit', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameField(
            model_name='gameresult',
            old_name='fit_u1',
            new_name='player1_fit',
        ),
        migrations.RenameField(
            model_name='gameresult',
            old_name='fit_u2',
            new_name='player1_score',
        ),
        migrations.RenameField(
            model_name='gameresult',
            old_name='user1_score',
            new_name='player2_fit',
        ),
        migrations.RenameField(
            model_name='gameresult',
            old_name='user2_score',
            new_name='player2_score',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='player1',
            field=models.CharField(default='user1', max_length=50),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='player2',
            field=models.CharField(default='user2', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='achievements',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consecutive_los',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consecutive_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='loss',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_consecutive_los',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_consecutive_wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='score_table',
            field=models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_game',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wins',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='winner',
            field=models.CharField(default='root', max_length=50),
        ),
    ]
