# Generated by Django 5.1.3 on 2024-12-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0035_userprofile_blocked_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='games',
            field=models.ManyToManyField(related_name='games', to='pages.gameresult'),
        ),
    ]
