# Generated by Django 5.1.3 on 2024-12-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_verificationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerStats',
        ),
        migrations.AddField(
            model_name='gameresult',
            name='imagePlayer1',
            field=models.ImageField(blank=True, default='profile_images/default_profile_image.jpg', null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='gameresult',
            name='imagePlayer2',
            field=models.ImageField(blank=True, default='profile_images/default_profile_image.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
