# Generated by Django 5.1.3 on 2024-12-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0039_gameresult_placeholder_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameresult',
            name='placeholder_user',
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='imagePlayer1',
            field=models.ImageField(blank=True, default='game_images/default_game_image.jpg', null=True, upload_to='game_images/'),
        ),
        migrations.AlterField(
            model_name='gameresult',
            name='imagePlayer2',
            field=models.ImageField(blank=True, default='game_images/default_game_image.jpg', null=True, upload_to='game_images/'),
        ),
    ]
