# Generated by Django 5.1.3 on 2024-12-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0041_blockedlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='trueUsername',
            field=models.CharField(default='', max_length=50),
        ),
    ]
