# Generated by Django 5.1.3 on 2024-12-13 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0042_userprofile_trueusername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='trueUsername',
        ),
    ]
